server:
  port: 8761
eureka:
  instance:
    # 主机名不配置的话默认为电脑名
    hostname: registry
    # 设置服务在注册时使用IP地址注册，而不是主机名称
    prefer-ip-address: true
  client:
    # 是否将自己注册到Eureka Server，默认为true。
    registerWithEureka: false
    # 是否从Eureka Server获取注册的服务信息,默认值true
    fetchRegistry: false
    serviceUrl:
      # Eureka服务器的地址，类型为HashMap，缺省的Key为 defaultZone；缺省的Value为 http://localhost:8761/eureka
      # 如果服务注册中心为高可用集群时，多个注册中心地址以逗号分隔。
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    # 服务名
    name: registry
