
server:
  port: 8001

spring:
  application:
    name: service-core
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    url: jdbc:mysql://127.0.0.1:3306/building_core?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: ROOT
    druid:
      initial-size: 10
      max-active: 20
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  # 执行mapper.xml文件位置
  mapper-locations: dao/**/*.xml
  configuration:
    # 打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #识别小驼峰
    map-underscore-to-camel-case: true
    #自动映射
    auto-mapping-behavior: full
  type-aliases-package: com.zhly.po



